# Generated by Django 5.1.4 on 2025-03-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_hotel_available_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_address',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_city',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_state',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_zipcode',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
