# Generated by Django 5.1.4 on 2025-03-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_hotel_hotel_address_hotel_hotel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='badge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
