# Generated by Django 5.1.4 on 2025-03-28 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_hotel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_image_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_category_name', models.CharField(blank=True, max_length=250, null=None)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel')),
            ],
        ),
    ]
