# Generated by Django 5.1.4 on 2025-03-28 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_hotel_image_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_all_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_img', models.ImageField(upload_to='hotel_all_image')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel')),
                ('img_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel_image_category')),
            ],
        ),
    ]
