# Generated by Django 5.1.4 on 2025-03-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_room_hotel_room_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_all_images',
            name='rooms_category',
        ),
    ]
