# Generated by Django 5.1.4 on 2025-03-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_room_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
