# Generated by Django 5.1.4 on 2025-03-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_room_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_category',
            name='cat_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
