# Generated by Django 5.1.7 on 2025-03-31 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_city_remove_hotel_hotel_city_influencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='app.city'),
        ),
    ]
